added support for the ZMQ_LAST_ENDPOINT option in zmq-get-socket-option
jerry40/guile-simple-zmq pull request #17
Opened 2021-02-25 21:43 UTC by Terramorpha

currently, running `(zmq-get-socket-option sock ZMQ_LAST_ENDPOINT)` throws an error due to the default size `(sizeof size_t)` this commit detects the `ZMQ_LAST_ENDPOINT` option, sets an appropriate buffer size and converts the opt bytevector back to a string.

2021-02-26 09:04 UTC, mothacehe requested changes
Hello,
Thanks for the patch, here are a few comments.
Mathieu

2021-02-26 09:04 UTC, mothacehe commented on simple-zmq.scm.in
> -			(display len) (newline)
you should squash this with the previous commit

2021-02-26 09:04 UTC, mothacehe commented on simple-zmq.scm.in
>  (define (zmq-get-socket-option socket option)
the indentation is wrong and there's a mix of spaces and tabulations

2021-02-26 09:04 UTC, mothacehe commented on simple-zmq.scm.in
> +					  ((eq? ZMQ_LAST_ENDPOINT option) 1024)
why 1024?

2021-02-26 09:04 UTC, mothacehe commented on simple-zmq.scm.in
> +
you can remove those

2021-02-26 09:04 UTC, mothacehe commented on simple-zmq.scm.in
> +			  (let ((new-bv (make-bytevector (1- len))))
I need to review it in more details but this seems quite complex

2021-02-27 14:06 UTC, Terramorpha commented
I made the changes you requested. I reindented the code using spaces, I squashed the commits and I removed the newline.
About your last comment, `zmq-get-socket-option` interprets the contents of the `opt` bytevector as an unsized integer. However, for the specific `ZMQ_LAST_ENDPOINT` option, it should interpret it as a string.
I added a special case for this.
The `1-`s are because the returned size takes into account the C string's null terminator.

2021-02-27 19:15 UTC, mothacehe commented
I added a few cosmetic changes, as well as the associated unit tests before pushing. Thanks!

2021-02-27 19:15 UTC, closed without merging